#cloud-config
apt_update: true
apt_upgrade: true
packages:
  - nginx
  - php
  - postgresql-13
  - pgadmin4
apt:
  sources:
    php8:
      source: "ppa:ondrej/php"
    postgresql13:
      source: "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
      keyid: 7FCC7D46ACCC4CF8
    pgadmin4:
      source: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4 main"
runcmd:
  - 'curl https://raw.githubusercontent.com/rafsodc/devenv/main/install/code-server.sh | /bin/bash -s'
  - 'curl https://raw.githubusercontent.com/rafsodc/devenv/main/install/nginx.sh | /bin/bash -s'
  - 'curl https://raw.githubusercontent.com/rafsodc/devenv/main/install/postgresql.sh | /bin/bash -s'
